language: node_js
node_js:
  - '8.8.1'
before_install:
  - npm install -g firebase-tools
  - npm firebase --version
install:
  - npm firebase --version
  - npm install
  - npm firebase --version
script:
  - npm firebase --version
  - npm run test
  - npm firebase --version
  - npm run build
  - npm firebase --version
after_success:
  - npm firebase --version
  -  firebase deploy  -- project myfinancetracker-ch  --token "$FIREBASE_TOKEN"