language: node_js
node_js:
  - '8.8.1'
install:
  - npm clean install
script:
  - npm run test
  - npm run build
after_success:
  -  firebase deploy  -- project myfinancetracker-ch  --token "$FIREBASE_TOKEN"