language: node_js
node_js:
  - '8.8.1'
cache:
  directories:
    - ".eslintcache"
    - "node_modules"
install:
  - npm install -g firebase-tools
script:
  - npm run test
  - npm run build
after_success:
  -  firebase deploy  -- project myfinancetracker-ch  --token "$FIREBASE_TOKEN"