language: node_js
node_js:
  - '8.8.1'
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
  - npm install
script:
  - npm run test
  - npm run build
after_success:
  - firebase deploy --project myfinancetracker-ch --token "$FIREBASE_TOKEN"